### ISSUE TITLE
API review & cleanup for 1.0

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-java#1594]
The following things should be implemented:

- [x] JSON methods currently wrap all runtime exceptions in a RealmException. Consider removing this as it makes it hard to know exactly what failed -> Remove RealmException where possible. ( #2618 )

- [x] Cleanup sorted* methods. Remove all sort methods accepting 3 fields. Multiarg should be used instead. ( #2619  )

- [x] Remove `allObjects` and friends from Realm so all query options are in RealmQuery. ( #2620 )

- [x] RealmConfiguration `setModules()` rename to `modules()` ( #2621 )

- [X] All lists methods should automatically do `copyToRealm` or `copyToRealmOrUpdate` (mc Checked, all methods which could add/change object in the list, will call `copyToRealmIfNeeded`)

- [ ] RealmChangeListener should provide the changes object/realm/collection as well

- [x] realm.createObject(class, primaryKey) should be public ( #2622 )

- [x] All methods on RealmObject should be final. All public Realm classes should be final (#2675).

- [x] BaseRealm should be package protected (will most likely require moving some things to `io.realm`) (#2673)

- [x] HandlerController should be package protected. ( #2632 )

- [x] Constructor of `RealmAsyncTask` should be package protected (#2676).

-----------

This issue help track any suggested refactoring, cleanup of the current API to prepare for 1.0 release.
this is not a call for feature, but a take on the existing API to rename/refactor.

please share your suggestions, it would be helpful to include motivation & code snippet/prototype so people can have a quick idea to up/down vote.

**Comment by cmelchior** [comment]
Some things on my list:

- Get rid of the difference between `copyToRealm` and `copyOrUpdateToRealm`. If your model class has primary keys just using `copyToRealm` doesn't make any sense. 

- Consider renaming `where` to `query` to get away from the SQL terminology.

**Comment by astigsen** [comment]
> Consider renaming `where` to `query` to get away from the SQL terminology.

In Swift the method is called `filter`, so it might be an idea to standardize on that?

**Comment by nhachicha** [comment]
As part of the 1.0 cleanup https://github.com/realm/realm-java-private/issues/21

**Comment by cmelchior** [comment]
This should also include formalising our Javadoc style and do a cleanup based on that.

**Comment by beeender** [comment]
* argument for `RealmChangeListener.onChange`
   * `RealmChangeListener.onChange(Realm)`
   * `RealmChangeListener.onChange(RealmObject)`
   * `RealmChangeListener.onChange(RealmResults)`

It would help user to reuse the listener after we support fine grained notification.

**Comment by cmelchior** [comment]
`addRealmChangeListener` should return the type being observed instead of `void`  for better fluent behavior:

```
RealmResults<Foo> foos = realm.where(Foo.class).findAllAsync().addChangeListener(() -> {});
foos.clearAllListeners(); // No need for to add listener, and really easy to unregister again to avoid leaks.
```

**Comment by cmelchior** [comment]
`@Index` vs. `@Indexed`

**Comment by cmelchior** [comment]
`@Ignore` vs. ` @Ignored`

**Comment by cmelchior** [comment]
Inheritance hierarchy with regard to DynamicRealmObject/RealmObject, RealmResults<DynamicRealmObject>, RealmResults<RealmObject> etc.

**Comment by cmelchior** [comment]
SQLite can just do `db.insert(...)` which is an implicit transaction.
Would it make sense to do the same for `copyToRealm` or `copyToRealmOrUpdate`, so you could just do:

```
Person p = new Person()
realm.copyToRealm(p);
```

**Comment by cmelchior** [comment]
Consider replacing @Ignore with the `transient` keyword instead

**Comment by cmelchior** [comment]
Right now the `List` interface methods `clear()/remove(int)/removeAll(collection)` mean different things across `RealmList`/`RealmResults`. This adds mental overhead to using Realm.

Also we have the methods `RealmObject.removeFromRealm()` and `RealmList.removeAllFromRealm()`.
It would be nice we we could somehow express better the difference between "removing from the list" vs. "removing from the list + remove it from Realm", while still being true to the original interfaces.

**Comment by beeender** [comment]
Consistency problem with `BaseRealm.beginTransaction()` `BaseRealm.commitTransaction` but `Realm.executeTransaction()`.

This could happen in the adapter which only hold a reference to a `RealmResults`.
User can do: 
```java
results.getRealm().beginTransaction();
restults.getRealm().commitTransaction();
```
but cannot do: 
```java
results.getRealm().executeTransaction();
```

**Comment by cmelchior** [comment]
Should the `findFirst` object be live just like a RealmQuery, aka. Should it be able to change completely. Right now once the "first" object has been found we only update _that_ object, we don't replace it, if another object becomes the "first"

**Comment by nhachicha** [comment]
some output from the API review I did with JP for Cocoa (16/03/2016)

- in Cocoa `distinct()` will be implemented using `NSPredicat` (not part of `RLMCollection`)

- Cocoa exposes an API to retrieve backlinks.
we don't have this on Java, Mark is working on it, changes needs to be add to Core then reflected on ObejctStore
maybe we should wait for ObjectStore integration before implementing this feature.

- in Cocoa `commitWrite`/ `commit` maybe recoverable in certain UC depending on Core exception type
Ex : `FileAccessError` (out of disk) we can make those checked Exceptions on Java

- update objects in bulk (something we don't have in Java) it's using `KVC`
the implementation avoid creating Objective-C accessors ==> more cheap 
it also keeps a frozen copy of the `table_view`

- ​_for-loop_​ behaves like frozen table_view (deep copy for accessors only to operate on)

- We don't have IN in Java ==> should be available in ObjectStore

- The async queries impl is different 
 two different behavior :
 1- first run block the UI thread, then subsequent updates happen in the background 
 2- you pass a callback & the user will have the Result when the first run completes
 all the subsequent updates happen in the background
no promise/future is returned

**Comment by cmelchior** [comment]
Remove `realm.createObject()`

**Comment by bdash** [comment]
> in Cocoa distinct() will be implemented using NSPredicate (not part of RLMCollection) -> #2118

I don't think this is quite right. NSPredicate's support for "distinct" is quite different than what Java's API provides, and cannot be used to achieve the same results as the Java API.

**Comment by jpsim** [comment]
> in Cocoa commitWrite/ commit maybe recoverable in certain UC depending on Core exception type
> Ex : FileAccessError (out of disk) we can make those checked Exceptions on Java -> Yes, but need list of specific core exceptions to map.

See realm/realm-cocoa#3437

**Comment by cmelchior** [comment]
All issues fixed. Closing

**Comment by iamaniba** [comment]
Is that [841](https://github.com/realm/realm-java/issues/841) fixed? Do we have any api to get Results based on list.
