### ISSUE TITLE
Cannot load `.so` file

### ISSUE THREAD

**Issue by kneth** [realm/realm-java#1634]
We have seen a number of issues regarding failure to load the .so file. This issue collects those separate issues reported:
Connects to #1527
Connects to #1534
Connects to #1421 (solved)
Connects to #1640 (ARM64 bug in AOSP)

TODO:
* [x] Document workaround for ARM64 bug in AOSP (#1640)
* [x] Document workaround for Google Analytics (#1421)
* [x] Understand the root cause of #1527 (update to latest Gradle plugin)
* [ ] Understand the root cause of #1534

**Comment by beeender** [comment]
https://realm.io/docs/java/latest/#couldnt-load-librealm-jniso Doc updated. But it seems #1527 and #1534 are not caused by 64-bit or gradle.
