### ISSUE TITLE
Realm.getInstanceAsync()

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#2299]
**Edit by CM**: Changing the focus slightly of this issue. Discussions around exposing info and callbacks for custom migrations have been moved to #4083 

---

As described in #4270 we need to expose a `Realm.getInstanceAsync(config)` in order to allow synced Realms to be downloaded first.

**Usage**
```java
// Create configuration
RealmConfiguration config = new RealmConfiguration.Builder()
  .migration(new MyMigration())
  .schemaVersion(42)
  .build();

// Get instance on a Looper thread
Realm.getInstanceAsync(config, new Realm.Callback() {
  public void OnSuccess(Realm realm) {
    // Use Realm
  }
  // Do we really want to force both onSuccess and onError?
  // Perhaps make Realm.Callback abstract and provide default impl for this?
  // Should we instead provide `getInstanceAsync(config, onSuccess, onError)`?
  public void onError(Exception e) {
    // Something went wrong? Migration failed, problems opening file?
  }
})
```

**TODO**
This issue is therefore now about the following:

- [x] Add new API `Realm.getInstanceAsync(config, callback)` and `DynamicRealm.getInstanceAsync(config, callback)`

- [x] If used, all schema validation and migration logic should run on the background thread to avoid blocking the UI thread at all. Once ready the caller thread should be allowed to open it's SharedRealm. I don't think there is any need to handover SharedRealm instances. I doubt it is supported in any case.

- [x] Should throw if called on a non-looper thread.
- [x] Unit tests
- [ ] Website docs

----

**Old description**
Since the migration could take some time it might block the UI, users probably needs to show a progress bar when that happens.
Also, an async `Realm.migrate(RealmConfiguration config, RealmCallback onSuccess)` will be very handy to this situation.

**Comment by cmelchior** [comment]
Adding a asynchronous initializer for Realm would also benefit startup times, and I have been thinking something along the same lines, but wouldn't an asynchronous `getInstance` be enough? Is there any use case for people needing to know when a migration is happening?

```
Realm.getInstanceAsync(config, onSuccess); 
Realm.getDefaultInstanceAsync(config, onSuccess); // We probably also need this one then?
```
vs.
```
Realm.isMigrationNeeded(config);
Realm.migrateRealm(config, onSuccess);

// Usage
if (Realm.isMigrationNeeded(config)) {
  Realm.migrateRealm(config, onsuccess);
} else {
  Realm.getInstance(config);
}
```

**Comment by beeender** [comment]
With:
```java
progressBar.show();
Realm.getInstanceAsync(config, -> 
    {
        progressBar.hide();
    }); 
```
the progress bar might be flashed in a very short time. User doesn't have control when some operation may/may not take a bit long time is not good IMO.

**Comment by beeender** [comment]
BTW, asynchronously to `getInstance` might be a bit complex to implement. 1) we need to hand over the `SharedGroup` which is created from another thead. 2) We need to deal the `RealmCache` to make sure the unique instance in the same thread.

**Comment by cmelchior** [comment]
Hmm, fair point. I guess if people really want to show a progress bar, there is no way around a wrapper class anyway.

My idea with async getInstance was mostly to offload migration + schema validation to another class. Getting the SharedGroup should still be done on the same thread.

**Comment by jjhesk** [comment]
can i still use this for removing all data if migration?

```java
   return new RealmConfiguration.Builder(app)
                .deleteRealmIfMigrationNeeded()
                .build();

```

**Comment by MohMah** [comment]
Hi, any news on this? cold start time gets very high when database grows and specially when there is a `transform` in the migration. Is there any solution right now that can be used?
thanks

**Comment by cmelchior** [comment]
No solution in the API right. Most sane approach is to have a wrapper around Realm that will run a migration on a background thread before allowing the UI thread to access it.

**Comment by cmelchior** [comment]
Reasons for adding something like `getInstanceAsync` now also comes from Sync with options like `SyncConfiguration.waitForServerChanges()` that doesn't open the Realm until all changes have been downloaded from the server.

**Comment by cmelchior** [comment]
Discussions around exposing info and callbacks for custom migrations have been moved to #4083 
As described in #4270 we need to expose a `Realm.getInstanceAsync(config)` in order to allow synced Realms to be downloaded first.

**Usage**
```java
// Create configuration
RealmConfiguration config = new RealmConfiguration.Builder()
  .migration(new MyMigration())
  .schemaVersion(42)
  .build();

// Get instance on a Looper thread
Realm.getInstanceAsync(config, new Realm.Callback() {
  public void OnSuccess(Realm realm) {
    // Use Realm
  }
  // Do we really want to pollute the API with this method?
  // Perhaps make Realm.Callback abstract and provide default impl for this?
  // Should we instead provide `getInstanceAsync(config, onSuccess, onError)`?
  public void onError(Exception e) {
    // Something went wrong? Migration failed, problems opening file?
  }
})
```

**TODO**
This issue is therefore now about the following:

- [ ] Add new API `Realm.getInstanceAsync(config, callback)` and `DynamicRealm.getInstanceAsync(config, callback)`

- [ ] If used, all schema validation and migration logic should run on the background thread to avoid blocking the UI thread at all. Once ready the caller thread should be allowed to open it's SharedRealm. I don't think there is any need to handover SharedRealm instances. I doubt it is supported in any case.

- [ ] Should throw if called on a non-looper thread.
- [ ] Unit tests
- [ ] Website docs

**Comment by beeender** [comment]
This requires some modifications in the Object Store as well. Since `RealmCoordinator` needs to save the thread id when after the `SharedGroup` is created for thread checking.

**Comment by cmelchior** [comment]
Why not just 

```
// API
RealmAsyncTask getInstanceAsync(RealmConfiguration config, OnSuccessCallback onSuccess);
RealmAsyncTask getInstanceAsync(RealmConfiguration config, OnSuccessCallback onSuccess, OnErrorCallback onError);

// Usage
RealmAsyncTask task = Realm.getInstanceAsync(config, listener);
RealmAsyncTask task = Realm.getInstanceAsync(config, listener); // Return the same task
task.cancel(); if you want to abort for some reason.
```

Having a non-loaded Realm instance feels a bit cumbersome to implement IMO, and it isn't something we would want to put into an UI element like the collections?

**Comment by beeender** [comment]
for the non-loaded Realm instance:
> When getInstance called with same configuration before the previous getInstanceAsync returns, a not-loaded instance will be returned immediately.

Then just throw in this case?

**Comment by cmelchior** [comment]
You cannot have a non-loaded instance in my API example? Until the task completes you only have the `RealmAsyncTask` ?

**Comment by beeender** [comment]
I mean, what if user do: 
```java 
RealmAsyncTask task = Realm.getInstanceAsync(config, onSuccess);
// Just throw here then?
Realm realm = Realm.getInstance();
```

**Comment by cmelchior** [comment]
Well, it would be rather stupid, but it would just work? It would be the equivalent of opening a Realm on two threads at the same time.

In the above case, I would probably log a warning in the log, just like we do when async queries are forced to be synchronous?

I guess you could argue that the above is such a big programming mistake that we should throw instead

**Comment by beeender** [comment]
no... it won't work ... it will just break the `RealmCache` design ... I will make it throw then -- with an non-loaded Realm instance, this will throw later as well. So yeah, throw it earlier will be a good idea.

**Comment by cmelchior** [comment]
I don't have a strong opinion. Throwing seems a bit harsh, but if not throwing would require substantial refactorings, then just throwing now seems fine. Then we can always re-evaluate if needed.

**Comment by beeender** [comment]
```java
Realm.getInstanceAsync(RealmConfiguration configuration, RealmInstanceCallback.OnSuccess<Realm> onSuccess);
Realm.getInstanceAsync(RealmConfiguration configuration, RealmInstanceCallback.OnSuccess<Realm> onSuccess, RealmInstanceCallback.OnError onError);
Realm.getDefaultInstance(RealmInstanceCallback.OnSuccess<Realm> onSuccess);
Realm.getDefaultInstance(RealmInstanceCallback.OnSuccess<Realm> onSuccess, RealmInstanceCallback.OnError onError);

DynamicRealm.getInstanceAsync(RealmConfiguration configuration, RealmInstanceCallback.OnSuccess<Realm> onSuccess);
DynamicRealm.getInstanceAsync(RealmConfiguration configuration, RealmInstanceCallback.OnSuccess<Realm> onSuccess, RealmInstanceCallback.OnError onError);
DynamicRealm.getDefaultInstance(RealmInstanceCallback.OnSuccess<Realm> onSuccess);
DynamicRealm.getDefaultInstance(RealmInstanceCallback.OnSuccess<Realm> onSuccess, RealmInstanceCallback.OnError onError);
```

8 methods for a single purpose, that looks very much redundant. But it is following the signature of `Realm.executeTransactionAsync()`.

What do you think? @realm/java

**Comment by cmelchior** [comment]
I would be tempted to say that this a power feature, so remove all the `Realm.getDefaultInstanceAsync()` variants, that would reduce it to 4 methods. What do you think?

**Comment by Zhuinden** [comment]
from https://github.com/realm/realm-java/pull/4570#discussion_r113699029

> I think I would prefer this being an inner class in Realm/DynamicRealm instead. This name is really long and fugly.
> 
> An inner class would enable us to do this:
> 
> Realm.getInstanceAsync(config, new Realm.Callback() {
>   @Override
>   public void onSuccess(Realm realm) {
>   }
> });
> Also we are fairly inconsistent with our callbacks. In some places we split OnSuccess/OnError into two interfaces (transactions), in other we combine them in one interface (network requests).
> 
> I would be tempted to say that for loading instances, people don't want to handle errors which for the sake of consistency would indicate two interfaces Realm.Callback.OnSuccess and Realm.Callback.OnError, this would also mean we need more getInstanceAsync() variants like we do for transactions.

**Comment by CriseX** [comment]
Please update your documentation/comments to not reference methods that do not actually exist :) (the example given in the release notes for 3.2.1 also does this). At a cursory glance this has not been mentioned elsewhere, but if so then nevermind.

**Comment by beeender** [comment]
@CriseX the doc has been added recently, see https://realm.io/docs/java/latest/#asynchronously-opening-realms some typos in the doc, i am fixing it right now.

**Comment by Zhuinden** [comment]
The javadocs still talk about `Realm.getDefaultInstanceAsync` in `Realm.Callback`.

https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/BaseRealm.java#L792

**Comment by dalinaum** [comment]
Thanks @Zhuinden I made a PR: #5119
