### ISSUE TITLE
Support Java on JVM

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-java#2339]
First task before we can add support for Java JVM is making sure our internal module structure/CI/deployment supports it.

Preliminary TODO list (we need to revisit this before starting development):

First task before we can add support for Java JVM is making sure our internal module structure/CI/deployment supports it.

Preliminary TODO list (we need to revisit this before starting development):

**Required**

- [ ] CI support to build core and sync binaries for different platforms. Needed for #2256 and #1867 as well.
 -- [x] Android (Already working)
 -- [x] Windows + Sync
 -- [x] MacOS + Sync
 -- [x] Linux + Sync (different variants?)

- [ ] We need to modify the build scripts to be able to generate versions for both Android and JVM.
-- [ ] We need to be able to build our JNI binding on multiple platforms. How to parallelize our Jenkinsfile to do this? Will also require specific mac support. Can we reuse how Core is doing it?

- [ ] CMake & reusing existing JNI code (current code is coupled with NDK toolchain) 
-- [ ] OpenSSL currently downloading the prebuilt package `libcrypto.a` for Android from https://github.com/realm/openssl-android [do] we need to adapt for macOS/Linux/Win?
-- [ ] Android specific flag ANDROID_NO_UNDEFINED, ABI_CXX_FLAGS, LINKER_FLAGS, `jni_impl/android_logger.cpp`
-- [ ] keep GCC 4.9 or use CLANG
-- [ ] Android Prebuilt Libraries (linkage): `-llog` `-landroid` `-latomic`
-- [ ] STL library `libc++`/`gnustl` 

- [ ] `realm-gradle-plugin` need to support two modes: `realm-android` and `realm-java`.
-- [ ] Rewrite in Kotlin?

- [ ] Split existing code into 3 modules: `realm-java-core`, `realm-java-android`, `realm-java-jvm` (names up for debate).
-- [ ] Need a new build.gradle for `realm-java-jvm`
-- [ ] Figure out how much code should live in each module

- [ ] Figure out how to run JavaAssist without the Transform API which is Android only.
-- [ ] How to share as much as possible between Transform API and JVM implementation?
-- [ ] Rewrite in Kotlin?

- [ ] All android dependencies need to be hidden behind interfaces.
-- [ ] Context needs to be abstracted away. Already begun in https://github.com/realm/realm-java/pull/3692. 
-- [ ] Our streaming Json support depends on Android classes as well
-- [ ] NetworkStateReceiver
-- [ ] `@RunTestInLooperThread`
-- [ ] We have quite a few unit tests with android dependencies.

- [ ] We need to figure out which run loops to support on the JVM, since the Looper does not exist. As a minimum, we need to provide our own.
-- [ ] Support for Spring event loop
-- [ ] Custom event loop for stand alone apps, e.g. Global Notifier
-- [ ] Web containers like Tomcat and friends don't have that concept. Just ignore them?

**Optional**

- [ ] Determine the need for a Maven plugin. If yes, we need to make that as well.
- [ ] Determine if API should be similar on JVM vs. Android. This especially impacts how much code can live in `realm-java-core`

**Comment by cmelchior** [comment]
This task should also consider if https://github.com/realm/realm-java/issues/1770 can be resolved at the same time.

**Comment by dickwu** [comment]
Is there any latest news about it?

**Comment by Zhuinden** [comment]
@dickwu parts of it have been implemented (for example the `AndroidNotifier` is what receives the looper's events and stuff), but I don't think it was truly a priority lately.

Especially with the whole 2.0.x release and the sync.

**Comment by marckaraujo** [comment]
This support will be released with 2.0.x?

**Comment by Zhuinden** [comment]
@marckaraujo Realm is at 2.2.2 at the moment, so that seems unlikely.

**Comment by jirungaray** [comment]
Are there any updates on this?

**Comment by Zhuinden** [comment]
Now with Realm-Core supporting UWP and Win32, this should actually be possible, although the question is *how do you know what event loop to use*.

**Comment by sluedecke** [comment]
I would be happy to see realm usable in a java desktop application.  It would enable a project of mine to migrate both app and desktop client from couchbase to realm (both app and desktop client share significant business logic which is currently located in a shared java library).

Also it would make realm potentially available in java application servers.

**Comment by jirungaray** [comment]
You guys have an awesome product but I decided to drop Realm because the lack of pure Java support which seems pretty low on the priority list. 

In my case the deal breakers were the inability to pre populate files server side and the android dependency which prevented some cross platform development (playing around with [Multi-OS Engine](https://multi-os-engine.org/)) .

Hope to get some better news next year so I can revisit the decision.

**Comment by sluedecke** [comment]
Would a workaround for server side pre-popluation like this work:

* have a read only realm A on the server available to all users
* on the first start of the app, create user specific realm B and copy things from A to B
* once done, remove all references on the device for realm A

?

**Comment by vivekkiran** [comment]
@cmelchior any updates on this?

**Comment by Zhuinden** [comment]
Purely special from my part, but post was last edited `on Oct 31, 2017`, and from the looks of it, it is absolutely not trivial. I'd wager it'd require pretty much a complete overhaul (unless current `realm-java` is rebranded to `realm-android` and then a similar but from-zero `realm-java-desktop` is created... :open_mouth: )

Maybe once stuff is done with the Realm Cloud thing that's happening, haha :smile:

**Comment by mataide** [comment]
We want this :+1:

**Comment by Aracher17** [comment]
I was about developing a diagnostic tool for our support team to have a look at customers database that they can run on their desktop (unfortunately the Realm Studio isn`t an option, but its existing let me grasp that there is a way to interact with a realm database on desktops). 
I understand that realm is specially designed for android but in our case, it would be great if we would have been able to write an own tool to interact with the realm database. 
Are there any updates? Any tricks on how to work with it in JVM on windows? 

It would be super awesome if someone could point out because I really feel like I missed something. 
Thank you and thank you for your great work! :)

**Comment by Zhuinden** [comment]
@Aracher17 I think you can make Realm work on Windows using C# API

They even added the `IsDynamic` flag with 2018-03-22 update, so you can *finally* read the schema of a Realm file from dotnet api

**Comment by bmunkholm** [comment]
Studio is written with plain realm-js and Electron - no special tricks. It will be open sourced soon btw.
And you could also use C# as mentioned.

**Comment by Aracher17** [comment]
I know that I‘ve missed something. Thank you @bmunkholm & @Zhuinden !!

**Comment by xiaobaiyey** [comment]
Any news on this? Anything that can be used from a JVM ?

**Comment by astatio** [comment]
Are there any news on this topic? It's been quite a while

**Comment by nathan-contino-mongo** [comment]
@astatio As far as I know, we don't have any plans to support the Java SDK on the JVM.

However, you can use the Kotlin Multiplatform SDK ([realm-kotlin](https://github.com/realm/realm-kotlin)) on the JVM: https://github.com/realm/realm-kotlin-samples/tree/main/JVMConsole
