### ISSUE TITLE
Integrate Object Store

### ISSUE THREAD

**Issue by kneth** [realm/realm-java#3148]
- [x] Base PR for making build work. See #3102
  - Enable cmake with our build system.
  - Enable cmake on CI.
  - Use git ~~subtree~~ submodule to integrate OS repo.
  - Use clang to compile since gcc 4.9 has problems with OS compiling.
  - Removing `realm-jni` won't be part of this to avoid conflicts. They can be remove after this merged to master.
- [x] Integrate SharedRealm from OS. See #3031
  - Replace `SharedGroup`/`Group` by `SharedRealm`.
  - More details see #3031.
- [ ] Integrate `Property`/`Schema`/`ObjectSchema`. (#3066)
- [x] Integrate OS notification (#3370)
- [x] Integrate `Results` for the future fine grained notification. (#3834)
- [x] Clean up finalizers? It is a good time to start it right now. (#3144)

Reviewing and merging #3102 is the basis of the integration.

**Comment by Zhuinden** [comment]
Hasn't `Integrate OS notification (#3370)` been merged?

**Comment by kneth** [comment]
Yes, I'll update.

**Comment by Zhuinden** [comment]
There is now https://github.com/realm/realm-java/pull/3834 for integrating Results

**Comment by cmelchior** [comment]
Last remaining task is the OS Schema integration. This is being tracked separately in #4324. Closing this.
