### ISSUE TITLE
SyncConfiguration.waitForServerChanges()

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#4270]
When using synced Realms it can sometimes be beneficial to wait until all changes from the server have been downloaded. Perhaps to avoid many rapid UI refreshes or because it only makes sense to view the data as a whole.

To address this issue we want to add two new API's:

1. New SyncConfiguration parameter: `SyncConfiguration.Builder.waitForServerChanges()`

This is a new boolean that enforces the behavior that it shouldn't be possible to open a Realm until  all changes have been downloaded. This should use the Object Store API described here: https://github.com/realm/realm-object-store/pull/385

* Setting this boolean will cause `getInstance(config)` to throw an Exception on the UI thread. It is probably okay to make blocking calls everywhere else.

* Setting this boolean should cause Realm to block the Realm file from being opened until the server says all changes have been downloaded.

2. New async method for opening instances: `Realm.getInstanceAsync(RealmConfiguration config)`

In order to provide access to Realms configured this way on the UI thread we need an async way of opening the Realm since network operations are not allowed there. Fortunately we already discussed the option of a `Realm.getInstanceAsync(config)` method: #2299 

This method should defer all long-running actions to a background Realm before allowing the caller thread to open the Realm instance. This includes: Validating the schema, running any migration logic, compacting (https://github.com/realm/realm-java/issues/3739) and downloading server changes as required. #2299 will be tracking that part.

**Usage:**
```java
// Create configuration
SyncConfiguration config = new SyncConfiguration.Builder(user, server)
  .waitForServerChanges()
  .build();

// Get instance on a Looper thread
Realm.getInstanceAsync(config, new Realm.Callback() {
  public void OnSuccess(Realm realm) {
    // Use Realm
  }
  // Do we really want to pollute the API with this method?
  // Perhaps make Realm.Callback abstract and provide default impl for this?
  // Should we instead provide `getInstanceAsync(config, onSuccess, onError)`?
  public void onError(Exception e) {
    // Something went wrong? 
  }
})

// Get instance on a background thread (blocking call)
// This must throw if on the UI thread
Realm realm = Realm.getInstance(config);
````

This issue tracks the 1st part. `getInstanceAsync()` is tracked here #2299 

The equivalent Cocoa implementation is tracked here: https://github.com/realm/realm-cocoa/pull/4681. Their implementation will differ a little due to different constraints. 

**TODO**
- [ ] Add new setting to `SyncConfiguration.Builder.waitForServerChanges()` ... Name is not set in stone, so can still be bikeshedded.
- [ ] Add `SyncConfiguration.willWaitForServerChanges()` getter.
- [ ] Setting this boolean should block the Realm from being opened until the server says it has all changes. This is naturally racy, so use the semantics defined by OS (determine "done" when starting download).
- [ ] Calling a blocking `getInstance()` should throw on the UI thread since networking isn't allowed there. 
- [ ] Decide if it is acceptable to make blocking calls on other Looper threads. Initial hunch would be yes.
- [ ] Decide how to handle being offline. Is it acceptable to wait indefinetetely, or perhaps provide a timeout using e.g `waitForServerChanges(1, TimeUnit.MINUTE), after which the Realm file will be opened anyway. It is still unclear if there is a use case for this, so can possible be punted.
- [ ] Unit tests
- [ ] Integration test towards Sync server.
- [ ] Website docs

**Comment by nhachicha** [comment]
- Might be off topic, but should we expose a `waitForServerChanges` option to make the API symmetric, this should set the stop policy to `SyncSessionStopPolicy::AfterChangesUploaded` in the ObjectStore so the sync::session can call `async_wait_for_upload_completion`

- `getInstanceAsync` might not be an appropriate name here, since we're not returning the Realm instance.
How about `Realm.openAsync` and/or `Realm.open`. of course both should return `RealmAsyncTask` in order to try to cancel the operation.

- How about reference counting? do we cache _async_ Realms ? what's the behaviour of a returned cached _async_ Realm?
knowing that after it was cached & retrieved again the server may produce other changeset that needs to be downloaded (in order to fulfil the `waitForServerChanges`  contract)

**Comment by cmelchior** [comment]
`waitForChangesUploaded` is probably something we would want to expose somehow, but I'm not sure the `RealmConfiguration` is the proper place, since that normally affect how a Realm is opened, and adding that would effect how it is closed. Also in a non-obvious way, e.g. should `close()` block until all changes are uploaded?

`getInstanceAsync` was mostly chosen because that is how our factory methods are named: `getDefaultInstance()`, `getInstance(config)`, so `getInstanceAsync` fit that category. It also fits how e.g `executeTransactionAsync` work.

Async realms should be reference counted the same way as normal Realms, the only difference is that all validation and migration should happen on a background thread. Since SharedRealms cannot be handed over across threads, there will probably some challenge involved in coordinating opening the SharedRealm on a background thread and when it has been prepared, close it again in order to re-open on the receiver thread. Possible we need to open on the receiver thread before closing on the worker thread to avoid room for race conditions.

Your right that caching an async Realm will come with some challenges when considering `waitForServerChanges`. Those will have to be solved as part of implementing this.

**Comment by nhachicha** [comment]
> should close() block until all changes are uploaded?

No. closing allow the OS to trigger the destructor of the SyncSession, this one will apply the policy specified. If the app/process is not exited it will still upload in the background (in case of `SyncSessionStopPolicy::AfterChangesUploaded`).

However there's currently no listener implemented, that allows the user to safely close the app after all changes have been uploaded. 

> async Realm will come with some challenges when considering waitForServerChanges

Main use case I'm worried about is what happen when you call again (in the same Thread)
```java
// Get instance on a Looper thread
Realm.getInstanceAsync(config, new Realm.Callback() {
  public void OnSuccess(Realm realm) {}
  public void onError(Exception e) {}
})
```
should this return immediately (i.e trigger `onSuccess`, since it's cached) or should it try to download again any new changesets ?

**Comment by cmelchior** [comment]
There are two cases here: 

**1) Async Realms with `waitForServerChanges()`** 
For these, we would always have to ask the server for changes, so we cannot cache these Realms the same we normally do I think. The Realm instance would have to be delivered along with other notifications.

**2) Async Realms without.**
For these, we can probably cache them, but IMO calling `onSuccess` straight away is a sure way of messing with people's timing I think, especially when setting up UI the first time. I have used other async API's that in some cases return immediately and you tend to forget that fact when writing the code, which easily leads to crashes.

Example: I have written code like the below in the past using such API's in the past (yes, I'm stupid 😄  ):
```java
private TextView v; 

protected void onCreated(SavedInstanceBundle b) {
  realm.addChangeListener(new RealmChangeListener() {
    @Override
    public void onChange(Realm realm) {
      uiElement.setText("changed"); // crashes because UI isn't initialized yet.
    }
  });
  uiElement = createDefaultView();
}
```

**Comment by nhachicha** [comment]
I agree, we should separate the Realm obtained asynchronously (to defer costly initialisations from UI thread) and the one with `waitForServerChanges()` that IMO shouldn't be cached.

`onSuccess` means the Realm is ready to be used. It's not our fault if the user uses this callback on the wrong UI Lifecycle. 

In the above example clearly the callback should be registered `onResume`. But I get your point being error prone `¯\_(ツ)_/¯`
```java
protected void onResume() {
  super.onResume();
  realm.addChangeListener(new RealmChangeListener() {
    @Override
    public void onChange(Realm realm) {
      uiElement.setText("changed"); 
    }
  });
}
```
