### ISSUE TITLE
Verify `@LinkingObjects` in dynamic and migration scenarios

### ISSUE THREAD

**Issue by bmeike** [realm/realm-java#4323]
#### Goal

Reliable, consistent `@LinkingObjectes`

There are, currently no Unit Tests for DynamicObjects that have `@LinkingObjects` fields, nor are there tests for migration scenarios.  There should be.

-----
### Tasks
- [x] Add UTs for dynamic objects
- [x] Add UTs for migration scenarios
- [x] How live are `RealmResults` and how should `ChangeListeners` be triggered ?
- [x] Consider how `CheckedRow` should handle BackLinks. 

#### Version of Realm and tooling

Realm version(s): 3.2

**Comment by cmelchior** [comment]
@bmeike Since @LinkingObject fields are not expressed in the Realm Schema, no migrations will be triggered either way. Is there anything left to do in this issue or can it just be closed?

**Comment by bmeike** [comment]
It can, probably, be closed.  This was a place-holder for a checkmark in the original Issue. Will verify ASAP.

**Comment by cmelchior** [comment]
@bmeike Any update on this?

**Comment by bmeike** [comment]
@zaki50 added a complete suite of DynamicRealm tests.  They are good to go.

**Comment by bmeike** [comment]
Opened a new ticket to track the last two, highly ephemeral items in this ticket
