### ISSUE TITLE
Mixed and dictionary data types

### ISSUE THREAD

**Issue by RealmBot** [realm/realm-java#6840]
Add support for Dictionary/Hashmap. See https://github.com/realm/realm-java/issues/759 for the initial discussion.

Possible API:
```
// New class
// See API for RealmResults/RealmList for which extra methods we need
class RealmMap<K, V> : Map<K,V> { ... }

// new change listener
class UnorderedCollectionChangeset {
  // Figure out API
}

// Example Usage
open class Person : RealmObject() {
  var map: RealmMap<String, Dog> = RealmMap()
}
val person = realm.createObject<Person>()
person.map.addChangelistener { map, changeset ->
  // Handle changes to map
}
```

### TODO (probably not complete):
-  [ ] Determine possible API. Ideally, we should be able to store all supported Realm types as both keys and values
- [ ] New callback type: `UnorderedCollectionChangeset`. Determine API.
- [ ] Add support for `RealmResults.setMap(map)`
- [ ] Add support for `DynamicRealmObject.setMap(map)`/`DynamicRealmObject.getMap()`.
- [ ] Add support in RealmFieldType
- [ ] Add support in RealmObjectSchema
- [ ] Add support in RealmQuery. Which types of queries should be supported? `containsKey/containsValue/containsEntry` ?

- [ ]  copyToRealm
- [ ]  copyToRealmOrUpdate
- [ ]  insert
- [ ]  insertOrUpdate
- [ ] copyFromRealm

- [ ] How should dictionaries be supported in JSON?
- [ ]  createObjectFromJson(Class, InputStream)
- [ ]  createObjectFromJson(Class, JSONObject)
- [ ]  createObjectFromJson(Class, String)
- [ ]  createOrUpdateObjectFromJson(Class, InputStream)
- [ ]  createOrUpdateObjectFromJson(Class, JSONObject)
- [ ]  createOrUpdateObjectFromJson(Class, String)
- [ ]  createAllFromJson(Class, InputStream)
- [ ]  createAllFromJson(Class, JSONArray)
- [ ]  createAllFromJson(Class, String)
- [ ]  createOrUpdateAllFromJson(Class, InputStream)
- [ ]  createOrUpdateAllFromJson(Class, JSONArray)
- [ ]  createOrUpdateAllFromJson(Class, String)

See https://github.com/realm/realm-java/pull/6722 for where changes need to happen

Blocked by https://github.com/realm/realm-core/issues/3717
