### ISSUE TITLE
Add support for Mixed

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#7075]
As part of adding support for Maps/Dictionaries we also need support for a new property type that functions like Mixed (PHP), Any (JS), or Object (Java) type.

## High level API
Needs to be determined, but see [https://docs.google.com/document/d/1ae2POUnTwX_FJPdAuEob0OwVoTsqYwOn2PbR7Q6MOmc/edit](https://docs.google.com/document/d/1ae2POUnTwX_FJPdAuEob0OwVoTsqYwOn2PbR7Q6MOmc/edit)

* [x] Figure out the name of the type. Should be aligned with other SDK's. Some suggestions so far: `RealmMixed`, `RealmAny`, `RealmValue`, `RealmDynamicValue`...
* [x] Figure out the exact API for this class. Should be aligned with other SDK's, but I suspect that `DynamicRealmObject` can be used as inspiration.
* [x] I believe the type it a value type, but needs to be verified. This has implications for change listeners and if they make sense on the type itself.
* [x] A property of type Mixed can be Indexed. Unclear if it can be marked as a primary key.
* [x] Unclear if Sorting or Distinct works on Mixed types.
* [x] In phase 1 we only support primitive and boxed types supported by Realm + single model references (but not embedded objects). Phase 2 will add support for Lists, Sets and Maps.
* [x] Unclear how query support should look like.

## TODO
* [x ] Add support in Annotation Processor.
* [x] Add support in copyToRealm(orUpdate)
* [x] Add support in insert(OrUpdate)
* [x] Add support in copyFromRealm
* [x] Add support in `RealmQuery`
* [x] Add support in `createFromJson` methods
* [x] Add support in `DynamicRealmObject`
* [x] `RealmList<Mixed>` is also supported. Extend unit tests and implementations.
* [x] RealmSchema
