### ISSUE TITLE
Add support for RealmMap

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#7077]
This issue tracks adding support for a new Map type. Name TBD, but RealmMap seems like the most obvious.

## High level API
Has not been finalized. This is just a first draft:

- [ ] Only String keys will be supported in Phase 1, but the API should be extensible to allow other types in the future.
 - [ ] Figure out which methods exist on Set
 - [ ] Figure out which additional methods make sense in a Realm setting: Change listeners, queries.
 - [  ] Maps of Lists, Sets, and Maps are not supported in Phase 1. Only Maps with values that areprimitive, boxed, Mixed, and single object references are supported. Embedded object not supported either.
- [ ] Figure out how the notifications should look like. Right now we `OrderedCollectionChangeSet`, with sets we should probably add `UnorderedCollectionChangeSet` but it is unclear how that should look like, also when it needs to support both Set and Maps.

```
// New types
public class RealmMap<K, V> implements Map<K,V> { /* ... */ }
public class RealmSet<V> implements Set<V> { /* ... */ }

// Property syntax
// Unsupported types will be caught by annotation processor at compile time
// It isn't possible to capture them directly in the type system.
public class Person extends RealmObject {
	// Maps (examples)
// Primitive type -> Primitive Type
	public RealmMap<Integer, String> map1 = new RealmMap<>();

// Object -> Primitive type 
	public RealmMap<Child, String> map2 = new RealmMap<>(); 

	// Sets
	public RealmSet<String> set1 = new RealmSet<>();
	public RealmSet<Child> set2 = new RealmSet<>();
}

// Query syntax. Haven't thought long about this and it is unclear exactly
// what is supported.
// Adding:
// - RealmQuery.containsKey(name, key)
// - RealmQuery.containsValue(name, value)
// - RealmQuery.containsEntry(name, Map.Entry<K,V> entry). 
// Anything more advanced probably requires subqueries like for lists?

realm.where(Person.class).containsKey("map1", 42).findAll()
realm.where(Person.class).containsValue("map1", "myValue").findAll()
realm.where(Person.class).containsEntry("map1", new Map.Entry(42, "myValue").findAll()

realm.where(Person.class).containsValue("set", 42).findAll()
```

## TODO

- [ ] Add support in Annotation Processor.
- [ ] Add support in copyToRealm(orUpdate)
- [ ] Add support in insert(OrUpdate)
- [ ] Add support in copyFromRealm
- [ ] Add support in `RealmQuery` 
- [ ] Add support in `createFromJson` methods
- [ ] Add support in `DynamicRealmObject`
