### ISSUE TITLE
Add RealmConfiguration.enableJavaUTF16CompatibiltyMode

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#7101]
Realm internally only allows UTF8 while Java operates with UTF16. For that reason, we convert Java Strings to UTF8 using the strict rules of UTF16 strings. Unfortunately, this can sometimes cause problems since Java allows illegal UTF16 Strings. For example, see https://github.com/realm/realm-java/issues/7081 where an illegal surrogate pair is encountered.

In Java when an illegal String (like invalid surrogate pair) is encountered and you try to print it, it will just replace the illegal surrogate with a `?` character instead of throwing. This effectively mask that some part of string has not been handled correctly, but also seems like a workable pragmatic approach.

Especially when you work solely on Android, using this pragmatic approach is probably better as it put how Realm works more in line with Java. For the sake of data consistency, it _should_ be an opt-in behavior though.

### TODO
- [ ] Figure out the exact name of the option, e.g. `automaticallyConvertIllegalUTF16Strings()`, `enableJavaUTF16CompatibiltyMode()` or something else.
- [ ] Make sure that the Javadoc for this method thoroughly describe the problem and what might happen if you enable this mode.
- [ ] Extend our UTF16 -> UTF8 converter to account for this when converting strings and replace illegal surrogates with `?`.
- [ ] Add entry to our FAQ about it.
